services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TODO
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  TodoList-API:
    image: todolist-api
    container_name: todolist-api
    ports:
      - 8000:8000
    depends_on:
      - postgres
volumes:
  postgres-data: